name: Hourly News Bot
on:
  schedule:
    - cron: '0 * * * *' # Runs every 1 hour
  workflow_dispatch: # To run from a button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install newspaper4k google-generativeai requests
      - name: Run Bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python auto_news.py
      - name: Push New Posts
        run: |
          git config user.name "Auto Bot"
          git config user.email "bot@example.com"
          git add content/posts/
          git commit -m "Auto Update: New Articles 2025" || exit 0
          git push

        











